option( PLATOMAIN     "Flag to turn on compilation of PlatoMain"           OFF )
option( PLATOSTATICS  "Flag to turn on compilation of Statics performer"    OFF )
option( ALBANY_MPMD   "Flag to turn on testing of Albany performer"         OFF )
option( ANALYZE_MPMD  "Flag to turn on testing of Plato Analyze performer"  OFF )
option( ALBANY        "Flag to turn on testing of Albany standalone"        OFF )
option( ANALYZE       "Flag to turn on testing of Plato Analyze standalone" OFF )
option( SEACAS        "Seacas tools"                                        OFF )

set(  PLATOMAIN_BINARY     PlatoMain     )
set(  PLATOSTATICS_BINARY  PlatoStatics  )
set(  ALBANY_MPMD_BINARY   AlbanyMPMD    )
set(  ANALYZE_MPMD_BINARY  LGR_MPMD      )
set(  ALBANY_BINARY        Albany        )
set(  ANALYZE_BINARY       lgr           )
