option( PLATOMAIN      "Flag to turn on testing of PlatoMain"                      OFF )
option( PLATOSTATICS   "Flag to turn on testing of Statics performer"              OFF )
option( PLATO_PYTHON   "Flag to turn on testing of Plato python interface"         OFF )
option( ALBANY_MPMD    "Flag to turn on testing of Albany performer"               OFF )
option( ANALYZE_MPMD   "Flag to turn on testing of Plato Analyze performer"        OFF )
option( ANALYZE_PYTHON "Flag to turn on testing of Plato Analyze python interface" OFF )
option( ALBANY         "Flag to turn on testing of Albany standalone"              OFF )
option( ANALYZE        "Flag to turn on testing of Plato Analyze standalone"       OFF )

set(  PLATOMAIN_BINARY     PlatoMain     )
set(  PLATOSTATICS_BINARY  PlatoStatics  )
set(  ALBANY_MPMD_BINARY   AlbanyMPMD    )
set(  ANALYZE_MPMD_BINARY  analyze_MPMD  )
set(  ALBANY_BINARY        Albany        )
set(  ANALYZE_BINARY       analyze       )
